# Generated by Django 2.2.3 on 2019-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getseat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
