# Generated by Django 2.2.4 on 2019-08-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getseat', '0002_train_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatsStatusSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('train_number', models.CharField(max_length=64)),
                ('departure_time', models.DateTimeField()),
                ('seats', models.CharField(max_length=255)),
            ],
        ),
    ]
